pipeline {
    agent { label '!docker-agent' }
    
    environment {
        APP_IMAGE = 'kotlin-scp-api:latest'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Checkmarx/Goatlin.git']]])
            }
        }
        
        stage ('SAST') {
            steps {
                // sh 'apt-get update && apt-get install -y wget'
                sh 'wget https://github.com/insidersec/insider/releases/download/2.1.0/insider_2.1.0_linux_x86_64.tar.gz'
                sh 'tar -xf insider_2.1.0_linux_x86_64.tar.gz' 
                sh 'chmod +x insider'
                sh './insider --tech android --target ./packages'
            }
        }

        stage ('Dependency-Check') {
            steps {  
                dependencyCheck additionalArguments: ''' 
                                    -o "./" 
                                    -s "./packages"
                                    -f "XML" 
                                    --prettyPrint''', odcInstallation: 'OWASP-DC'

                dependencyCheckPublisher pattern: 'dependency-check-report.xml'
                }
            }
        
        stage ('Build docker image') {
            steps{
                script{
                    app = docker.build(env.APP_IMAGE, './packages/services/api')
                }
            }
        }
        
        stage ('Scan docker image') {
            steps{

                sh 'curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b .'
                sh './trivy image --exit-code 0 --no-progress $APP_IMAGE'
            }
        }

        stage ('DAST') {
            steps{
                script{
                    docker.image('mongo:5.0.6-focal').withRun('--name db --expose 27017') { c1->
                        docker.image('kotlin-scp-api').withRun('--name api --link db:db -p 8080:8080') {c2->
                            docker.image('owasp/zap2docker-stable').inside('--link api:api -v ${WORKSPACE}:/zap/wrk/:rw') {
                                sh 'zap-full-scan.py -t http://api:8080 -J zap.json'    
                            }
                        }
                    }
                }
            }
        }         

    }

    post {
        always {
            archiveArtifacts artifacts: 'zap.json', followSymlinks: false
        }
    }
}