pipeline {
    // agent { label 'docker-agent' }
    
    agent any
    environment {
        APP_IMAGE = 'kotlin-scp-api:latest'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Checkmarx/Goatlin.git']]])
            }
        }
        
        stage ('SAST') {
            steps {
                // sh 'apt-get update && apt-get install -y wget'
                sh 'wget https://github.com/insidersec/insider/releases/download/2.1.0/insider_2.1.0_linux_x86_64.tar.gz'
                sh 'tar -xf insider_2.1.0_linux_x86_64.tar.gz' 
                sh 'chmod +x insider'
                sh './insider --tech android --target ./packages'
            }
        }

        stage ('OWASP Dependency-Check Vulnerabilities') {
            steps {  
                dependencyCheck additionalArguments: ''' 
                                    -o "./" 
                                    -s "./packages"
                                    -f "XML" 
                                    --prettyPrint''', odcInstallation: 'OWASP-DC'

                dependencyCheckPublisher pattern: 'dependency-check-report.xml'
                }
            }
        
        stage ('Build docker image') {
            steps{
                script{
                    app = docker.build(env.APP_IMAGE, "./packages/services/api")
                }
            }
        }
        
        stage ('Scan docker image') {
            steps{

                sh 'curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b .'
                sh './trivy image --exit-code 0 --no-progress $APP_IMAGE'
            }
        }       

    }
}